FROM nginx
WORKDIR /home/
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./server.c .
COPY ./run.sh .
RUN chmod +x run.sh \
    && apt update \
    && apt install -y gcc spawn-fcgi libfcgi-dev
ENTRYPOINT ["./run.sh"]